name: check triggers

on:
  workflow_dispatch:
  schedule:
  - cron: "30 23 * * *"

jobs:
  raw-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        echo "downloading yq"
        python -m pip install --upgrade pip
        pip install yq
        yq --version

        KUSTOMIZE=5.1.1
        echo "downloading kustomize ${KUSTOMIZE}"
        curl -sL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE}/kustomize_v${KUSTOMIZE}_linux_amd64.tar.gz | \
        tar xz && mv kustomize /usr/local/bin/kustomize
        kustomize version
    - name: Check last upstream version
      id: lastrelease
      run: |
        get_latest_release() {
          curl -s "https://api.github.com/repos/tektoncd/triggers/releases" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'|head -n 1
        }
        echo "latest_tag=$(get_latest_release)" >> $GITHUB_OUTPUT
    - name: execute hack
      id: hack
      env:
        RELEASE: ${{ steps.lastrelease.outputs.latest_tag }}
      run: |
        cd deploy
        ../hack/new-release.sh ${RELEASE}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Update to version ${{ steps.lastrelease.outputs.latest_tag }}
        branch: main
        file_pattern: deploy/*.yaml
        tagging_message: ${{ steps.lastrelease.outputs.latest_tag }}
